spring.application.name=baby-bonus-enrollment
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
api.key=${API_KEY}
logging.file.name=logs/baby-bonus-enrollment.log
logging.logback.rollingpolicy.file-name-pattern=logs/baby-bonus-enrollment-%d{yyyy-MM-dd}.log
logging.logback.rollingpolicy.max-history=30
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [caller=%X{caller}] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [caller=%X{caller}] %logger{36} - %msg%n
